config/routes.rb
Rails.application.routes.draw do



  resources :entries, :only => [:show, :edit, :destroy, :update] do
    
    resources :recordings, :only => [:create]

  end

  resources :dictionaries do
    resources :entries, :only => [:new, :create]

    resources :collaborators, :only => [:create, :destroy]
  end

  resources :users


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout'  => 'sessions#destroy'



  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home' => 'static_pages#home'

  root 'static_pages#home'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessor :lemmata

  before_validation :initialize_lemmata

  belongs_to :dictionary

  has_and_belongs_to_many :lemmas, -> { uniq }

  has_many :recordings

  validates :lemmas,
            presence: true

  validates :dictionary,
            presence: true

  accepts_nested_attributes_for :lemmas

  def lemmata
    @new_lemmata_str || self.lemmas.map {|l| l.text}
  end

  def lemmata=(strings)
    @new_lemmata_str = strings
  end

  def initialize_lemmata

    add = @new_lemmata_str - self.lemmas.map {|l| l.text}

    self.lemmas.each do |lemma|
      unless @new_lemmata_str.include? lemma.text
        self.lemmas.delete lemma
      end
    end

    add.each do |new_lemma_str|
      self.lemmas.append(Lemma.find_or_initialize_by(text: new_lemma_str))
      logger.debug 'before save adding ' + new_lemma_str
    end

    
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_filter :restrict_access
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_dictionary, except: [:edit, :update]

  # GET /entries/1
  def show
    root_path unless current_user.can_view_dictionary(@entry.dictionary)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    root_path unless current_user.can_change_entries(@entry.dictionary)
  end

  # POST /entries
  def create
    root_path unless current_user.can_create_entries(@entry.dictionary)

    @entry = Entry.new(entry_params)

    lemmata_strings = params[:entry][:lemmata]
                      .strip.split("\n").map {|s| s.strip}

    @entry.lemmata = lemmata_strings

    @entry.dictionary = @dictionary

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /entries/1
  def update
    root_path unless current_user.can_change_entries(@entry.dictionary)

    lemmata_strings = params[:entry][:lemmata]
                      .strip.split("\n").map {|s| s.strip}

    @entry.lemmata = lemmata_strings

    logger.info "lemmata: " + @entry.lemmata.to_s

    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /entries/1
  def destroy
    root_path unless current_user.can_delete_entries(@dictionary)

    @entry.destroy
    respond_to do |format|
      format.html { redirect_to @dictionary, notice: 'Entry was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.includes(:recordings, :lemmas).find_by_id(params[:id])
    end

    def set_dictionary
      @dictionary = Dictionary.find_by_id(params[:dictionary_id])
      if @dictionary.nil?
        @dictionary = @entry.dictionary
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:content)
    end

    def restrict_access
      unless logged_in
        redirect_to login_path
      end
    end


end

app/helpers/entries_helper.rb
module EntriesHelper
    def article_for_display(article)
      article.gsub(/[\r\n]/, '<br>').html_safe
    end
end

app/views/entries/_form.html.erb
<%= form_for([@dictionary, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-md-4">
      <fieldset class="form-group">
	<%= f.label :lemmata %>
	<%= text_area_tag 'entry[lemmata]', @entry.lemmata.join("\n"), {class: 'form-control'} %>
	<p class="text-muted">
	  Add one key word or lemma per line.
	</p>
      </fieldset>
    </div>
    <div class="col-md-8">

      <fieldset class="form-group">
	<%= f.label :content %><br>
	<%= f.text_area :content, class: 'form-control' %>
      </fieldset>
    </div>

  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<script type="text/javascript">
  var recordings = <%= @entry.recordings.map {|r| {'id'=>r.id, 'user_id' => r.user_id, 'user_name' => r.user.name}}.to_json.html_safe %>;
</script>

<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
  <li class=""><%= link_to @entry.dictionary.name, @entry.dictionary %></li>
  <li class="active"><%= link_to 'Edit Entry', '#' %></li>
</ol>

<h1>Editing Entry</h1>

<%= render 'form' %>

<div class="row">
  <div class="col-xs-4">
    <div id="audio-panel"></div>
  </div>
  <div class="col-xs-8">
    <div id="recordings-list"></div>
  </div>
</div>

<input type="hidden" id="entry_id" value="<%= @entry.id %>">

<%= link_to 'Remove', @entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Dictionary</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.dictionary %></td>
        <td><%= entry.content %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
  <li class=""><%= link_to @dictionary.name, @dictionary %></li>
  <li class="active"><%= link_to 'New Entry', '#' %></li>
</ol>

<%= render 'form' %>

app/views/entries/show.html.erb
<script type="text/javascript">
  var recordings = <%= @entry.recordings.map {|r| {'id'=>r.id, 'user_id' => r.user_id, 'user_name' => r.user.name}}.to_json.html_safe %>;
</script>

<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
  <li class=""><%= link_to @dictionary.name, @dictionary %></li>
  <li class="active"><%= link_to 'Entry', '#' %></li>
</ol>


<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">Key words</div>

      
      <div class="list-group">
	<% @entry.lemmas.each do |lemma| %>
	<div class="list-group-item"><%= lemma.text %></div>
	<% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card card-block">
      <h4 class="card-title">Article</h4>
      <p class="card-text">
	<%= article_for_display(@entry.content) %>
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-4">
    <div id="audio-panel" class="hidden-xs-up" style=""></div>
  </div>
  <div class="col-xs-offset-4 col-xs-8">
    <div id="recordings-list"></div>
  </div>
</div>

<% if current_user.can_change_entries(@entry.dictionary) %>
<%= link_to 'Edit', edit_entry_path(@entry), class: 'btn btn-primary' %> 
<% end %>