config/routes.rb
Rails.application.routes.draw do



  resources :entries, :only => [:show, :edit, :destroy, :update] do
    
    resources :recordings, :only => [:create]

  end

  resources :dictionaries do
    resources :entries, :only => [:new, :create]

    resources :collaborators, :only => [:create, :destroy]
  end

  resources :users


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout'  => 'sessions#destroy'



  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home' => 'static_pages#home'

  root 'static_pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }

  validates :name,
            presence: true,
            length: { minimum: 3, maximum: 30 },
            uniqueness: { case_sensitive: false }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  has_many :dictionaries

  has_secure_password


  def can_view_dictionary(dictionary)


    return true if dictionary.user == self

    return true if dictionary.public

    collaborator = Collaborator.find_by(dictionary: dictionary,
                                        user: self)

    !collaborator.nil?
  end

  def can_create_entries(dictionary)
    return true if dictionary.user == self

    collaborator = Collaborator.find_by(dictionary: dictionary,
                                        user: self)

    collaborator && collaborator.can_create_entries
  end

  def can_change_entries(dictionary)
    unless dictionary.class.to_s === 'Dictionary'
      raise 'must provide a dictionary, got ' + dictionary.class.to_s
    end

    return true if dictionary.user == self

    collaborator = Collaborator.find_by(dictionary: dictionary,
                                        user: self)

    collaborator && collaborator.can_change_entries
  end

  def can_delete_entries(dictionary)
    return true if dictionary.user == self

    collaborator = Collaborator.find_by(dictionary: dictionary,
                                        user: self)

    collaborator && collaborator.can_delete_entries
  end

  def authenticated?(remember_token)
    return false if rememmber_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def remember
    self.remember_token = 0
    update_attribute(:remember_digest, 0)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :restrict_access, except: [:new, :create]
  before_filter :is_account_owner, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @dictionaries_collaborating =
      Dictionary.includes(:collaborators).where(collaborators: {user_id: @user.id})
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end

    def restrict_access
      unless logged_in
        redirect_to login_path
      end
    end

    def is_account_owner
      unless current_user === @user
        redirect_to root_path
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label' %>
    <%= f.email_field :email, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label' %>
    <%= f.text_field :password, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-block'  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<ol class="breadcrumb">
  <li class="active"><%= link_to "Users", users_path %></li>
</ol>

<h1>Users</h1>

<ul class="list-group">
  <% @users.each do |user| %>
  <%= link_to user.name, user, class: 'list-group-item' %>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>

    <%= render 'form' %>
    <p>If you already have an account, <%= link_to "log in", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<ol class="breadcrumb">
  <li class=""><%= link_to "Users", users_path %></li>
  <li class="active"><%= link_to @user.name, user_path(@user) %></li>
</ol>

<h1><%= @user.name %>'s profile</h1>

<p>
  <strong>Member since:</strong>
  <%= @user.created_at.to_formatted_s(:short) %>
</p>

<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
	Dictionaries this user created
      </div>
      <% if @user.dictionaries.size > 0 %>
      <table class="table table-condensed">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Entries</th>
	  </tr>
	</thead>
	<tbody>
	  <% @user.dictionaries.each do |dictionary| %>
	  <tr>
	    <td><%= link_to dictionary.name, dictionary %></td>
	    <td><%= dictionary.entries.count %></td>
	  </tr>
	  <% end %>
	</tbody>
      </table>
      <% else %>
      <div class="card-block">
	<p class="card-text">
	  This user has not yet created any dictionaries.
	</p>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
	Dictionaries this user contributes to 
      </div>
      <% if @dictionaries_collaborating.size > 0 %>
      <table class="table table-condensed">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Entries</th>
	  </tr>
	</thead>
	<tbody>
	  <% @dictionaries_collaborating.each do |dictionary| %>
	  <tr>
	    <td><%= link_to dictionary.name, dictionary %></td>
	    <td><%= dictionary.entries.count %></td>
	  </tr>
	  <% end %>
	</tbody>
      </table>
      <% else %>
      <div class="card-block">
	<p class="card-text">
	  This user is not involved in any dictionary projects.
	</p>
      </div>
      <% end %>
    </div>
  </div>
</div>