config/routes.rb
Rails.application.routes.draw do



  resources :entries, :only => [:show, :edit, :destroy, :update] do
    
    resources :recordings, :only => [:create]

  end

  resources :dictionaries do
    resources :entries, :only => [:new, :create]

    resources :collaborators, :only => [:create, :destroy]
  end

  resources :users


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout'  => 'sessions#destroy'



  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home' => 'static_pages#home'

  root 'static_pages#home'
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  has_many :entries

  has_many :collaborators

  has_many :users, through: :collaborators

  belongs_to :user

  validates :name,
            presence: true,
            length: { minimum: 3, maximum: 50 }

  validates :user,
            presence: true

  accepts_nested_attributes_for :collaborators, update_only: true

end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_filter :restrict_access

  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  def index
    @dictionaries = Dictionary.where(public: true)
  end

  # GET /dictionaries/1
  def show

    root_path unless current_user.can_view_dictionary(@dictionary)

    respond_to do |format|

      format.html

      format.babylon { render 'dictionaries/show.babylon.erb',
                              layout: false,
                              content_type: 'text/plain' }

      format.xdxf { render 'dictionaries/show.xdxf.erb',
                           layout: false,
                           content_type: 'text/xml' }
    end    
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
    redirect_to root_path unless @dictionary.user == current_user

  end

  # POST /dictionaries
  def create
    redirect_to root_path unless @dictionary.user == current_user


    @dictionary = Dictionary.new(dictionary_params)

    @dictionary.user = current_user

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  def update
    redirect_to root_path unless @dictionary.user == current_user

    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /dictionaries/1
  def destroy
    redirect_to root_path unless @dictionary.user == current_user

    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary
                    .includes(entries: [:lemmas] )
                    .find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params
        .require(:dictionary)
        .permit(:name, :description, :public,
                collaborators_attributes: [:user_id,
                                           :id,
                                           :can_create_entries,
                                           :can_change_entries,
                                           :can_delete_entries])
    end

    def restrict_access
      unless logged_in
        redirect_to login_path
      end
    end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.erb
<div class="card card-block">

  <%= form_for(@dictionary) do |f| %>
  <% if @dictionary.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

    <ul>
      <% @dictionary.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :public %>
      public
    </label>
    <p class="help-block">If this check box is ticked, everybody will be able to see the dictionary.</p>
  </div>



  <% if action_name == 'edit' %>
  <div class="card">
    <div class="card-header">
      Permissions
    </div>
    <table class="table">
      <thead>
	<tr>
	  <th>Name</th>
	  <th><span class="small">Can create entries</span></th>
	  <th><span class="small">Can edit entries</span></th>
	  <th><span class="small">Can delete entries</span></th>
	</tr>
      </thead>
      <tbody>

	<%= f.fields_for(:collaborators) do |collaborator_f| %>
	<%= collaborator_f.hidden_field :user_id, :value => collaborator_f.object.user_id %>
	<tr>
	  <td><%= link_to collaborator_f.object.user.name, collaborator_f.object.user %></td>
	  <td><%= collaborator_f.check_box :can_create_entries %></td>
	  <td><%= collaborator_f.check_box :can_change_entries %></td>
	  <td><%= collaborator_f.check_box :can_delete_entries %></td>
	</tr>

	<% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/dictionaries/edit.html.erb
<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
  <li><%= link_to @dictionary.name, @dictionary %></li>
  <li class="active"><%= link_to 'Edit Dictionary', '#' %></li>
</ol>

<h1>Editing Dictionary</h1>


<%= render 'form' %>



<div class="card">
  <div class="card-header">
    Add a new collaborator
  </div>
  <div class="card-block">
    <%= form_tag dictionary_collaborators_path(@dictionary) do %>
    <div class="form-group">
      <%= label_tag :name, nil, {class: 'control-label'} %>
      <%= text_field_tag :name, nil, {class: 'form-control'} %>
      <p class="help-block">Initially only the owner of a dictionary can create and change entries.  If you want to allow another use to modify the dictionary, enter their name into the input field and click on the button.  If a user with this name exists, they will become a <em>collaborator</em>.</p>
    </div>
    <%= submit_tag nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>


<%= link_to 'Remove', @dictionary, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/dictionaries/index.html.erb
<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
</ol>

<h1>Dictionaries</h1>

<div class="row">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">Available dictionaries</div>
      <table class="table table-striped">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Created</th>
	    <th>#entries</th>
	    <th>#contributors</th>
	  </tr>
	</thead>

	<tbody>
	  <% @dictionaries.each do |dictionary| %>
	  <tr>
            <td><%= link_to dictionary.name, dictionary %></td>
	    <td><%= dictionary.created_at.to_formatted_s(:short) %></td>
	    <td><%= dictionary.entries.count %></td>
	    <td><%= dictionary.collaborators.count + 1 %></td>
	  </tr>
	  <% end %>
	</tbody>
      </table>
    </div>
  </div>
  <div class="col-md-3">
    <div class="btn-group-vertical btn-block" role="group">
      <%= link_to 'New Dictionary', new_dictionary_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/dictionaries/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Dictionaries", dictionaries_path %></li>
  <li class="active"><%= link_to 'New dictionary', new_dictionary_path %></li>
</ol>

<h1>New Dictionary</h1>

<%= render 'form' %>

app/views/dictionaries/show.babylon.erb
#bookname=<%= @dictionary.name %>
#author=Unknown
#description=<% @dictionary.description %>

<% @dictionary.entries.each do |entry| %>
<%= entry.lemmas.map {|l| l.text}.join('|') %>
<%= entry.content.gsub(/[\n\r]/, '<br>') %>

<% end %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li class=""><%= link_to "Dictionaries", dictionaries_path %></li>
  <li class="active"><%= link_to @dictionary.name, @dictionary %></li>
</ol>

<h1><%= @dictionary.name %></h1>

     
  

<div class="row">

  <div class="col-md-9">
    <table class="table table-striped">
      <thead>
	<tr>
	  <th>Lemma</th>
	  <th>Article</th>
	</tr>
      </thead>
      <tbody>
	<% @dictionary.entries.each do |entry| %>
	<tr>
	  <td><%= entry.lemmas.first.text %></td>
	  <td><%= link_to article_for_display(entry.content), entry %></td>
	</tr>
	<% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-3">
    <p><strong>Creator:</strong> <%= link_to @dictionary.user.name, @dictionary.user %></p>
    <p>
      <strong>Contributors:</strong>
      <%= @dictionary.users.map { |user| link_to user.name, user }.join(', ').html_safe %>
    </p>
    <p>
      <strong>Created:</strong>
      <%= @dictionary.created_at.to_formatted_s(:short) %>
    </p>


    <div class="btn-group-vertical btn-block" role="group">
      <% if current_user.can_create_entries(@dictionary) %>
      <%= link_to 'New Entry', new_dictionary_entry_path(@dictionary), class: 'btn btn-primary' %>
      <% end %>

      <% if @dictionary.user == current_user %>
      <%= link_to 'Edit', edit_dictionary_path(@dictionary), class: 'btn btn-primary' %>
      <% end %>

      <%= link_to 'Export to Babylon', dictionary_path(@dictionary, format: :babylon), class: 'btn btn-secondary' %>

      <%= link_to 'Export to XDXF', dictionary_path(@dictionary, format: :xdxf), class: 'btn btn-secondary' %>

    </div>
  </div>

</div>

app/views/dictionaries/show.xdxf.erb
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE xdxf SYSTEM "https://raw.github.com/soshial/xdxf_makedict/master/format_standard/xdxf_strict.dtd">
<xdxf lang_from="ENG" lang_to="ENG" format="logical" revision="032beta">
    <meta_info>
        <title><%= @dictionary.name %></title>
        <full_title><%= @dictionary.name %></full_title>
        <description><%= @dictionary.description %></description>
        <abbreviations>
          <abbr_def><abbr_k>n.</abbr_k><abbr_v>noun</abbr_v></abbr_def>
          <abbr_def><abbr_k>v.</abbr_k><abbr_v>verb</abbr_v></abbr_def>
          <abbr_def><abbr_k>Av.</abbr_k><abbr_k>Ave.</abbr_k><abbr_v>Avenue</abbr_v> </abbr_def>
        </abbreviations>
        <file_ver>001</file_ver>
        <creation_date><%= @dictionary.created_at.strftime("%m-%d-%Y") %></creation_date>
    </meta_info>
    <lexicon>
    <% @dictionary.entries.each do |entry| %>
        <ar>
	<% entry.lemmata.each do |lemma| %>
	 <k><%= lemma %></k>
        <% end %>	
            <def>
                <deftext><%= entry.content %></deftext>
            </def>
        </ar>
	<% end %>
    </lexicon>
</xdxf>