config/routes.rb
Rails.application.routes.draw do



  resources :entries, :only => [:show, :edit, :destroy, :update] do
    
    resources :recordings, :only => [:create]

  end

  resources :dictionaries do
    resources :entries, :only => [:new, :create]

    resources :collaborators, :only => [:create, :destroy]
  end

  resources :users


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout'  => 'sessions#destroy'



  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home' => 'static_pages#home'

  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= Rails.application.config.name %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-primary">
  <%= link_to Rails.application.config.name, root_path, class: 'navbar-brand' %>
  <ul class="nav navbar-nav">
    <li class="nav-item"><%= link_to "Home", root_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "Dictionaries", dictionaries_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "Users", users_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to "FAQ", faq_path, class: 'nav-link'  %></li>

    <% if logged_in %>
    <li class="nav-item"><%= link_to "Log out", logout_path, method: :delete, class: 'nav-link'  %></li>
    <% else %>
    <li class="nav-item"><%= link_to "Sign up", signup_path, class: 'nav-link'  %></li>
    <li class="nav-item"><%= link_to "Log in", login_path, class: 'nav-link'  %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.application.config.name %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-no-turbolink>
    <%= render 'layouts/header' %>
    <% if notice %>
    <div class="card card-block">
      <p id="notice" class="card-text"><%= notice %></p>
    </div>
    <% end %>
    <div class="container"><%= yield %></div>
    <%= render 'layouts/footer' %>
  </body>
</html>